### ISSUE TITLE
If routing strategy can also apply to VFI tasks?

### ISSUE THREAD

**Issue by Eric-chuan** [megvii-research/CVPR2023-DMVFN#1]
Hi, congratulations on this latest achievement of yours. Your block selection strategy based on routing vectors can alleviate the difference between training and inference very well, I would like to ask if this strategy is also available for video interpolation tasks.

**Comment by hzwer** [comment]
Hi, I think we can try it out on tasks related to optical flow. My research direction has recently shifted to the Large Language Model, and Xiaotao Hu will continue to develop video prediction models. We have no plans to conduct this research in the short term.
