### ISSUE TITLE
The size of the images of the training and the test was inconsistent

### ISSUE THREAD

**Issue by xuesongnie** [megvii-research/CVPR2023-DMVFN#3]
Hello, this is a great job! I noticed that the paper says to resize the image of the dataset, which is 1024×512 in Cityscapes and 256×832 in KITTI. It was found that the picture would be intercepted to 256×256 in the training stage why not enter the whole picture, but the entire images was included in the testing stage, why the size of the images of the training and the test was inconsistent?
`training stage: imgs = self.aug_seq(imgs, 256, 256)`
`testing stage: imgs = Full-size image`

**Comment by huxiaotaostasy** [comment]
Thank you for your question. In the low-level field, previous researches are done in the same way as this setting (training on small images, testing on full-size). When training, if you use the full-size, it will cause problems such as too small batchsize, out-of-memory, and slow training.
