### ISSUE TITLE
A small bug, I'm not sure how to fix it. 

### ISSUE THREAD

**Issue by xuejy19** [megvii-research/CVPR2023-DMVFN#5]
I'm confused in dataset/dataset.py,line 275, for i in range(len(frame_list), self.timestep). First of all, len(frame_list) is much larger than self.timestep. Obviously, this line of code is incorrect. I assume that the author meant to write "for i in range(0, len(frame_list), self.timestep)." However, a new problem arises because the number of images in each subfolder of UCF101 is different. When constructing the dataset, errors will occur when using DataLoader to divide batches. I would like to know how the author solved this problem at the time.

**Comment by huxiaotaostasy** [comment]
Thanks for your question and I'm sorry for the mistake I made and its impact. I have updated it. https://github.com/megvii-research/CVPR2023-DMVFN/blob/main/dataset/dataset.py#L269 .

**Comment by xuejy19** [comment]
Thanks for your answer! Because some of the video frames have less than 50 images (the minimum number of images is 29), I believe that modifying max_time = 5 to max_time = 5 if 5 <= n/10 else int(n/10) might be better. Thanks again.

**Comment by huxiaotaostasy** [comment]
My UCF dataset is stored in the cloud, and it takes a day to copy to the local, and I forgot the minimum number of images was 29 (I just remember that some videos don't have many frames), thank you, I have updated it.
