### ISSUE TITLE
about FLOPS (not issue, but question)

### ISSUE THREAD

**Issue by FykAikawa** [megvii-research/CVPR2023-DMVFN#9]
Thank you for sharing awesome model!
I want to know how did you calculated the FLOPS of your model.
Did you use some tools to calculate it?
I would like to appreciate if you could share information about it.
Thank you.

**Comment by huxiaotaostasy** [comment]
Thank you for your question. 
We used fvcore to calculate FLOPs.
It was developed by Facebook Research.
here is the link https://github.com/facebookresearch/fvcore/ .

**Comment by FykAikawa** [comment]
Thank you for your reply!
I'll try it.
I really appreciate your reply,
